export interface Quote { text: string; author: string }

export const QUOTES: Quote[] = [
  // ── Pilar I · Acción ──────────────────────────────────────────────────────
  { text: "La disciplina es el puente entre las metas y los logros.", author: "Jim Rohn" },
  { text: "Solo el hombre que es dueño de sí mismo es libre.", author: "Epicteto" },
  { text: "No tienes que ser grande para empezar, pero tienes que empezar para ser grande.", author: "Zig Ziglar" },
  { text: "La excelencia no es un acto, sino un hábito.", author: "Aristóteles" },
  { text: "La motivación te pone en marcha, el hábito te mantiene en movimiento.", author: "Jim Ryun" },
  { text: "La libertad es lo que haces con lo que te han hecho.", author: "Jean-Paul Sartre" },
  { text: "El genio es 1% inspiración y 99% transpiración.", author: "Thomas Edison" },
  { text: "No mires el reloj; haz lo que él hace. Sigue moviéndote.", author: "Sam Levenson" },
  { text: "La victoria pertenece al más perseverante.", author: "Napoleón Bonaparte" },
  { text: "La soberanía sobre uno mismo es el mayor de los imperios.", author: "Séneca" },
  { text: "Hazlo o no lo hagas, pero no lo intentes.", author: "Maestro Yoda" },
  { text: "El que tiene un porqué para vivir puede soportar casi cualquier cómo.", author: "Viktor Frankl" },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que más quieres.", author: "Abraham Lincoln" },
  { text: "El que no puede obedecerse a sí mismo, será mandado.", author: "Friedrich Nietzsche" },
  { text: "La acción es la clave fundamental de todo éxito.", author: "Pablo Picasso" },
  { text: "Nuestra mayor debilidad radica en rendirnos. La forma más segura de tener éxito es intentarlo una vez más.", author: "Thomas Edison" },
  { text: "El coraje no es tener la fuerza para seguir adelante; es seguir adelante cuando no tienes fuerza.", author: "Theodore Roosevelt" },
  { text: "Pequeñas disciplinas repetidas con constancia cada día conducen a grandes logros adquiridos con el tiempo.", author: "John C. Maxwell" },
  { text: "Si no diseñas tu propio plan de vida, es probable que caigas en el plan de otra persona.", author: "Jim Rohn" },
  { text: "La pereza viaja tan despacio que la pobreza pronto la alcanza.", author: "Benjamin Franklin" },
  { text: "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.", author: "Séneca" },
  { text: "El hombre que mueve montañas empieza apartando piedrecitas.", author: "Confucio" },
  { text: "La diligencia es la madre de la buena fortuna.", author: "Miguel de Cervantes" },

  // ── Pilar II · Mente ──────────────────────────────────────────────────────
  { text: "El viento apaga la vela pero aviva el fuego.", author: "Nassim Taleb" },
  { text: "No es lo que te sucede, sino cómo reaccionas a ello lo que importa.", author: "Epicteto" },
  { text: "El obstáculo es el camino.", author: "Marco Aurelio" },
  { text: "Si estás pasando por un infierno, sigue adelante.", author: "Winston Churchill" },
  { text: "La mayor gloria no es nunca caer, sino levantarse siempre.", author: "Confucio" },
  { text: "Lo que no me mata, me hace más fuerte.", author: "Friedrich Nietzsche" },
  { text: "Ningún mar en calma hizo experto a un marinero.", author: "Proverbio Inglés" },
  { text: "El dolor es inevitable, el sufrimiento es opcional.", author: "Buda" },
  { text: "Tú tienes poder sobre tu mente, no sobre los eventos externos. Siente esto y encontrarás la fuerza.", author: "Marco Aurelio" },
  { text: "La resiliencia es ver que hay luz a pesar de toda la oscuridad.", author: "Desmond Tutu" },
  { text: "La joya no puede ser pulida sin fricción, ni el hombre perfeccionado sin pruebas.", author: "Proverbio Chino" },
  { text: "Busca la libertad y conviértete en cautivo de tus deseos. Busca la disciplina y encuentra tu libertad.", author: "Koan Zen" },
  { text: "No sufras por el pasado, no te preocupes por el futuro; concéntrate en el momento presente.", author: "Buda" },
  { text: "La adversidad es el primer camino hacia la verdad.", author: "Lord Byron" },
  { text: "Si no puedes cambiar tu destino, cambia tu actitud.", author: "Amy Tan" },
  { text: "Un hombre que sufre antes de que sea necesario, sufre más de lo necesario.", author: "Séneca" },
  { text: "La calma es el trono de la sabiduría.", author: "J.G. Holland" },
  { text: "A veces la vida te pega en la cabeza con un ladrillo. No pierdas la fe.", author: "Steve Jobs" },
  { text: "En medio de la dificultad reside la oportunidad.", author: "Albert Einstein" },
  { text: "El hombre es afectado no por los eventos, sino por la visión que tiene de ellos.", author: "Epicteto" },
  { text: "No dejes que el comportamiento de otros destruya tu paz interior.", author: "Dalai Lama" },
  { text: "Nuestra vida es lo que nuestros pensamientos crean.", author: "Marco Aurelio" },
  { text: "La resiliencia es el arte de navegar en los torrentes.", author: "Boris Cyrulnik" },
  { text: "Tu mente es como el agua: cuando está agitada es difícil ver, pero si permites que se asiente, la respuesta se vuelve clara.", author: "Cita Zen" },
  { text: "El bambú que se dobla es más fuerte que el roble que resiste y se rompe.", author: "Proverbio Japonés" },

  // ── Pilar III · Crecimiento ───────────────────────────────────────────────
  { text: "Quien mira hacia afuera, sueña; quien mira hacia adentro, despierta.", author: "Carl Jung" },
  { text: "La educación emocional es la base de todo progreso humano.", author: "Daniel Goleman" },
  { text: "La vulnerabilidad es el lugar donde nace la innovación, la creatividad y el cambio.", author: "Brené Brown" },
  { text: "El crecimiento comienza al final de tu zona de confort.", author: "Neale Donald Walsch" },
  { text: "Si quieres cambiar el mundo, cámbiate a ti mismo.", author: "Mahatma Gandhi" },
  { text: "Lo que niegas te somete. Lo que aceptas te transforma.", author: "Carl Jung" },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
  { text: "Sé el cambio que quieres ver en el mundo.", author: "Gandhi" },
  { text: "Conocerse a uno mismo es el principio de toda sabiduría.", author: "Aristóteles" },
  { text: "Aquel que tiene un gran dominio sobre sí mismo, es verdaderamente libre.", author: "Francisco de Quevedo" },
  { text: "No es el cambio lo que produce dolor, sino la resistencia a él.", author: "Buda" },
  { text: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", author: "Nelson Mandela" },
  { text: "La paradoja curiosa es que cuando me acepto tal como soy, entonces puedo cambiar.", author: "Carl Rogers" },
  { text: "El analfabeto del futuro no será la persona que no sepa leer, sino la que no sepa aprender, desaprender y reaprender.", author: "Alvin Toffler" },
  { text: "No te compares con nadie más, compárate con quien eras ayer.", author: "Jordan Peterson" },
  { text: "Para cambiar tu vida, necesitas cambiar tus prioridades.", author: "Mark Twain" },
  { text: "Cada vez que somos capaces de decir 'no' a un impulso, estamos diciendo 'sí' a nuestra propia evolución.", author: "Anónimo" },

  // ── Pilar IV · Logro ──────────────────────────────────────────────────────
  { text: "La mejor forma de predecir el futuro es creándolo.", author: "Peter Drucker" },
  { text: "La integridad es hacer lo correcto incluso cuando nadie está mirando.", author: "C.S. Lewis" },
  { text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.", author: "Albert Schweitzer" },
  { text: "Un camino de mil millas comienza con un solo paso.", author: "Lao Tse" },
  { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
  { text: "Apunta a la luna. Si fallas, podrías dar a una estrella.", author: "William Clement Stone" },
  { text: "Tu tiempo es limitado, de modo que no lo malgastes viviendo la vida de alguien distinto.", author: "Steve Jobs" },
  { text: "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.", author: "Winston Churchill" },
  { text: "La visión sin acción es simplemente un sueño.", author: "Joel Barker" },
  { text: "Siembra un acto y cosecharás un hábito. Siembra un hábito y cosecharás un carácter.", author: "Charles Reade" },
  { text: "Vive como si fueras a morir mañana. Aprende como si fueras a vivir siempre.", author: "Gandhi" },
  { text: "Lo que haces hoy puede mejorar todos tus mañanas.", author: "Ralph Marston" },
  { text: "La visión sin ejecución es alucinación.", author: "Thomas Edison" },
  { text: "El futuro pertenece a quienes creen en la belleza de sus sueños.", author: "Eleanor Roosevelt" },
  { text: "Aquel que planta árboles, sabiendo que nunca se sentará a su sombra, ha empezado a entender el sentido de la vida.", author: "Rabindranath Tagore" },
  { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
  { text: "No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.", author: "Robert Louis Stevenson" },
  { text: "Siempre parece imposible hasta que se hace.", author: "Nelson Mandela" },
  { text: "No intentes convertirte en un hombre de éxito, sino en un hombre de valor.", author: "Albert Einstein" },

  // ── Estoicismo ────────────────────────────────────────────────────────────
  { text: "No es que tengamos poco tiempo, sino que perdemos mucho.", author: "Séneca" },
  { text: "La fortuna no teme a los valientes, sino a los que se rinden.", author: "Séneca" },
  { text: "A menudo sufrimos más por nuestra imaginación que por la realidad.", author: "Séneca" },
  { text: "No hay árbol recio ni robusto sino aquel que el viento azota con frecuencia.", author: "Séneca" },
  { text: "El fuego prueba el oro; la miseria, a los hombres fuertes.", author: "Séneca" },
  { text: "Languidece la virtud sin un adversario.", author: "Séneca" },
  { text: "Comienza a vivir de inmediato y cuenta cada día como una vida separada.", author: "Séneca" },
  { text: "El obstáculo que bloquea el camino se convierte en el camino.", author: "Marco Aurelio" },
  { text: "Tienes poder sobre tu mente, no sobre los eventos externos. Date cuenta de esto y encontrarás la fuerza.", author: "Marco Aurelio" },
  { text: "No pierdas más tiempo discutiendo lo que debe ser un buen hombre. Sé uno.", author: "Marco Aurelio" },
  { text: "La vida es más parecida a la lucha que a la danza.", author: "Marco Aurelio" },
  { text: "Si un hombre no sabe hacia qué puerto navega, ningún viento le es favorable.", author: "Séneca" },
  { text: "No son las cosas las que nos perturban, sino nuestras opiniones sobre ellas.", author: "Epicteto" },
  { text: "Primero dite a ti mismo quién quieres ser; luego haz lo que tengas que hacer.", author: "Epicteto" },
  { text: "Nadie es libre si no es dueño de sí mismo.", author: "Epicteto" },
  { text: "No esperes que los eventos sucedan como deseas. Desea que sucedan como suceden y tu vida fluirá bien.", author: "Epicteto" },
  { text: "El control de tu mente es el único control que realmente importa.", author: "Epicteto" },
  { text: "Toda maestría requiere el olvido de la comodidad.", author: "Epicteto" },
  { text: "Aquel que es capaz de dominarse a sí mismo es capaz de dominar cualquier cosa.", author: "Epicteto" },
  { text: "El destino guía a quienes están dispuestos y arrastra a quienes se resisten.", author: "Cleantes" },
  { text: "Ningún hombre es más infeliz que aquel que nunca se enfrenta a la adversidad.", author: "Séneca" },
  { text: "No es porque las cosas sean difíciles que no nos atrevemos; es porque no nos atrevemos que son difíciles.", author: "Séneca" },
  { text: "Un hombre sabio se esfuerza por ser dueño de sus acciones, no de sus resultados.", author: "Marco Aurelio" },
  { text: "Trata cada esfuerzo como si fuera el último de tu vida.", author: "Marco Aurelio" },
  { text: "La mejor venganza es ser diferente de quien causó el daño.", author: "Marco Aurelio" },
  { text: "Sé como la roca en la que las olas se rompen continuamente. Ella se mantiene firme y el furor del mar se calma a sus pies.", author: "Marco Aurelio" },

  // ── Proverbios Orientales ─────────────────────────────────────────────────
  { text: "Si te caes siete veces, levántate ocho.", author: "Proverbio Japonés" },
  { text: "El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.", author: "Proverbio Chino" },
  { text: "No temas ir despacio, teme solo detenerte.", author: "Proverbio Chino" },
  { text: "El viento no puede vencer a un árbol que tiene raíces profundas.", author: "Proverbio Chino" },
  { text: "Quien ha movido la montaña es quien comenzó quitando las piedras pequeñas.", author: "Proverbio Chino" },
  { text: "Las grandes almas tienen voluntades; las débiles solo tienen deseos.", author: "Proverbio Chino" },
  { text: "La persona que dice que no se puede hacer no debe interrumpir a la persona que lo está haciendo.", author: "Proverbio Chino" },
  { text: "No importa qué tan lento vayas, siempre y cuando no te detengas.", author: "Confucio" },
  { text: "El guerrero más poderoso es aquel que se vence a sí mismo en silencio.", author: "Confucio" },

  // ── Ciencia y Lógica ──────────────────────────────────────────────────────
  { text: "Locura es hacer lo mismo una y otra vez esperando obtener resultados diferentes.", author: "Albert Einstein" },
  { text: "Si he logrado ver más lejos, ha sido porque he subido a hombros de gigantes.", author: "Isaac Newton" },
  { text: "No tengo talentos especiales, pero sí soy profundamente curioso.", author: "Albert Einstein" },
  { text: "La medida de la inteligencia es la capacidad de cambiar.", author: "Albert Einstein" },
  { text: "El genio es paciencia eterna.", author: "Miguel Ángel" },
  { text: "No fracasé. Solo encontré 10,000 formas que no funcionaban.", author: "Thomas Edison" },
  { text: "No es que sea muy inteligente, es que me quedo con los problemas más tiempo.", author: "Albert Einstein" },
  { text: "No temo al hombre que ha lanzado 10,000 patadas diferentes, temo al hombre que ha lanzado una patada 10,000 veces.", author: "Bruce Lee" },

  // ── Determinación ─────────────────────────────────────────────────────────
  { text: "Nada es imposible, la palabra misma dice 'soy posible'.", author: "Audrey Hepburn" },
  { text: "La determinación es el punto de partida de todo logro.", author: "W. Clement Stone" },
  { text: "Cree que puedes y ya estarás a medio camino.", author: "Theodore Roosevelt" },
  { text: "Si puedes soñarlo, puedes hacerlo.", author: "Walt Disney" },
  { text: "No te detengas cuando estés cansado, detente cuando hayas terminado.", author: "David Goggins" },
  { text: "Los límites, como el miedo, a menudo son solo una ilusión.", author: "Michael Jordan" },
  { text: "Lo que la mente puede concebir y creer, la mente puede lograr.", author: "Napoleon Hill" },
  { text: "Solo aquellos que se arriesgan a ir demasiado lejos pueden descubrir hasta dónde se puede llegar.", author: "T.S. Eliot" },
  { text: "El éxito no es el final, el fracaso no es fatal: es el coraje de continuar lo que cuenta.", author: "Winston Churchill" },
  { text: "El mundo rompe a todos, y después, muchos son fuertes en los lugares rotos.", author: "Ernest Hemingway" },
  { text: "Si no te rindes, tienes una oportunidad. Rendirse es el único fracaso real.", author: "Jack Ma" },
  { text: "La perseverancia es fallar 19 veces y tener éxito en la vigésima.", author: "Julie Andrews" },
  { text: "Solo aquellos que se atreven a fallar miserablemente pueden lograr mucho.", author: "Robert F. Kennedy" },
  { text: "Para tener éxito, primero debemos creer que podemos.", author: "Nikos Kazantzakis" },
  { text: "La mayoría de las personas abandonan justo antes de que ocurra el milagro. No seas la mayoría.", author: "Anónimo" },

  // ── Disciplina ────────────────────────────────────────────────────────────
  { text: "La disciplina es el recordatorio diario de lo que realmente quieres.", author: "Anónimo" },
  { text: "Haz hoy lo que otros no quieren, para mañana lograr lo que otros no pueden.", author: "Jerry Rice" },
  { text: "La autodisciplina es cuando tu consciencia te dice que hagas algo y no le discutes.", author: "W.K. Hope" },
  { text: "La disciplina pesa gramos, el arrepentimiento pesa toneladas.", author: "Jim Rohn" },
  { text: "No busques motivación, busca disciplina. La motivación falla, la disciplina cumple.", author: "Anónimo" },
  { text: "Un hombre con disciplina es un hombre con poder ilimitado.", author: "Anónimo" },
  { text: "Tu disciplina debe ser tan fuerte que tus propios demonios te tengan respeto.", author: "Anónimo" },
  { text: "La disciplina no es un castigo, es el entrenamiento para tu libertad futura.", author: "Anónimo" },
  { text: "El éxito es simplemente la aplicación diaria de la disciplina.", author: "Jim Rohn" },
  { text: "La disciplina es hacer lo que odias como si lo amaras, solo porque sabes que es necesario.", author: "Mike Tyson" },
  { text: "La disciplina es el combustible que permite a la gente común lograr resultados extraordinarios.", author: "Anónimo" },
  { text: "La constancia es la hija de la disciplina y la madre del éxito.", author: "Anónimo" },

  // ── Constancia ────────────────────────────────────────────────────────────
  { text: "La gota de agua perfora la roca, no por su fuerza, sino por su constancia.", author: "Ovidio" },
  { text: "La constancia es el complemento indispensable de todas las demás virtudes humanas.", author: "Giuseppe Mazzini" },
  { text: "El éxito es la constancia del propósito.", author: "Benjamin Disraeli" },
  { text: "La paciencia y la perseverancia tienen un efecto mágico ante el cual las dificultades desaparecen.", author: "John Quincy Adams" },
  { text: "La excelencia no es un evento aislado, es la suma de la constancia diaria.", author: "Anónimo" },
  { text: "El río corta la roca no porque sea poderoso, sino porque es constante.", author: "Anónimo" },
  { text: "Ser constante es ser fiel a tus sueños cuando el entusiasmo inicial desaparece.", author: "Anónimo" },
  { text: "La constancia te permite fallar mil veces y ganar la definitiva.", author: "Anónimo" },
  { text: "No busques ser el mejor de un día, busca ser el más constante de la década.", author: "Anónimo" },
  { text: "Los grandes trabajos no se gestionan por la fuerza, sino por la perseverancia.", author: "Samuel Johnson" },
  { text: "La perseverancia es el trabajo duro que haces después de cansarte del trabajo duro que ya hiciste.", author: "Newt Gingrich" },

  // ── Resiliencia ───────────────────────────────────────────────────────────
  { text: "Eres una máquina de resiliencia diseñada para convertir la presión en diamantes.", author: "Anónimo" },
  { text: "El cansancio es temporal, la satisfacción de lograrlo es para siempre.", author: "Anónimo" },
  { text: "Si fuera fácil, todos lo harían. La dificultad es el filtro que separa a los ganadores de los espectadores.", author: "Anónimo" },
  { text: "Cuando sientas que te vas a rendir, recuerda por qué empezaste.", author: "Anónimo" },
  { text: "El dolor que sientes hoy será la fuerza que sientas mañana.", author: "Anónimo" },
  { text: "No eres una víctima de las circunstancias, eres el resultado de tus decisiones.", author: "Anónimo" },
  { text: "El fracaso es solo un moretón, no un tatuaje.", author: "Jon Sinclair" },
  { text: "La resiliencia no es aguantar el golpe, es usar la energía del impacto para levantarse más rápido.", author: "Anónimo" },
  { text: "La resiliencia se construye en los días en que no quieres levantarte, pero lo haces de todos modos.", author: "Anónimo" },
  { text: "La fuerza interna es el único combustible que no se agota con el uso; se fortalece.", author: "Anónimo" },
  { text: "Si te cansas, aprende a descansar, no a rendirte.", author: "Banksy" },
  { text: "No vine hasta aquí para solo llegar hasta aquí.", author: "Anónimo" },

  // ── Voluntad ──────────────────────────────────────────────────────────────
  { text: "Lo voy a lograr porque mi voluntad de ganar es mayor que mi miedo a fallar.", author: "Anónimo" },
  { text: "No soy lo que me pasó, soy lo que elegí ser hoy.", author: "Carl Jung" },
  { text: "Si el camino es difícil es porque vas en la dirección correcta.", author: "Anónimo" },
  { text: "Tu mente te dirá que pares 100 veces. Tu corazón te dirá que sigas una vez más. Hazle caso al corazón.", author: "Anónimo" },
  { text: "La duda es un mentiroso; la disciplina es la verdad.", author: "Anónimo" },
  { text: "Mi meta es clara, mi esfuerzo es total, mi éxito es inevitable.", author: "Anónimo" },
  { text: "Hoy no es el día para rendirse. Mañana tampoco.", author: "Anónimo" },
  { text: "La voluntad es el músculo que más debes entrenar en el gimnasio de la vida.", author: "Anónimo" },
  { text: "El guerrero más poderoso es aquel que se vence a sí mismo.", author: "Anónimo" },
  { text: "Eres más fuerte de lo que crees, más capaz de lo que imaginas y más resiliente de lo que te permites ser.", author: "Anónimo" },
  { text: "Voy a lograrlo. Mi disciplina es mi garantía.", author: "Anónimo" },
  { text: "Cierra la boca, baja la cabeza y trabaja hasta que tus resultados hablen por ti.", author: "Anónimo" },
  { text: "La gloria se construye en el anonimato del esfuerzo diario.", author: "Anónimo" },
  { text: "Eres el capitán de tu esfuerzo y el dueño de tu constancia. Navega.", author: "Anónimo" },
  { text: "Lo voy a lograr. Punto.", author: "Anónimo" },
  { text: "Cada repetición, cada minuto de esfuerzo es un ladrillo en mi imperio.", author: "Anónimo" },
  { text: "La mente es un excelente servidor pero un terrible amo. Domínala con disciplina.", author: "Anónimo" },
  { text: "Voy a lograrlo porque me niego a aceptar cualquier otro resultado.", author: "Anónimo" },
  { text: "Tu determinación de hoy es el mapa de tus logros de mañana.", author: "Anónimo" },
]
